spring:
  application:
    name: golosseum
  batch:
    job:
      enabled: false
  datasource-meta:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:tcp://localhost:9092/~/meta_db'
    username: sa
    password:
  datasource-data:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:tcp://localhost:9092/~/data_db'
    username: sa
    password: